### ISSUE TITLE
Error with docker image

### ISSUE THREAD

**Issue by Comique** [oscartbeaumont/netlify-dynamic-dns#67] opened 2024-02-26 02:42 UTC
Error: Error Updating DNS Record error retrieving your public ipv6 address: dial udp [2620:119:35::35]:53: connect: cannot assign requested address
Error reporting anonymous analytics data:  error posting analytics event: Post "https://analytics.otbeaumont.me/event": x509: certificate is valid for *.netlify.app, netlify.app, not analytics.otbeaumont.me

Running it with
docker run ghcr.io/oscartbeaumont/netlify-dynamic-dns:latest -accesstoken <token> -zone <domain> -record home -interval 5

**Comment by oscartbeaumont** [comment] 2024-11-19 04:54
I think this is a duplicate of #69 which should now be fixed.

**Closed by oscartbeaumont** 2024-11-19 04:54 UTC
