### ISSUE TITLE
Docker image not found

### ISSUE THREAD

**Issue by JD10NN3** [oscartbeaumont/netlify-dynamic-dns#12] opened 2021-03-31 12:22 UTC
You mention a way to do it with Docker but it look like your package can't be found.

**Comment by oscartbeaumont** [comment] 2021-03-31 12:28
Have you tried the command in the README?
In case you can't see it: ```docker run ghcr.io/oscartbeaumont/netlify-dynamic-dns:latest -accesstoken xxx -zone example.com -record home -interval 5```
I currently don't have access to a machine with Docker but if the above command is not working let me know and I will investigate when I can.

**Comment by rahul003** [comment] 2021-07-29 05:59
This command doesn't work. I tried logging in with Github credentials as well. It seems like the image isn't available, is it?

**Comment by oscartbeaumont** [comment] 2021-07-30 02:06
I have reopened this issue as I am receiving `Error response from daemon: Head https://ghcr.io/v2/oscartbeaumont/netlify-dynamic-dns/manifests/v3.0.0: unauthorized` when attempting to pull the image. As the image should be able to be pulled without authentication this is weird and I will look into it.

**Comment by oscartbeaumont** [comment] 2021-07-30 02:20
This issue should be fixed. It was caused by:
 - The container's permissions being separate from the GitHub repository (I didn't realise) and being set to private.
 - Also no Docker `latest` tag is set by default so I manually push the latest container to the latest tag.

**Closed by oscartbeaumont** 2021-07-30 02:20 UTC

**Comment by rahul003** [comment] 2021-07-30 03:17
Thanks!
